[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "llm-utils"
version = "0.2.1"
authors = [
  { name="Nicolas van Kempen", email="nvankemp@gmail.com" },
  { name="Emery Berger", email="emery.berger@gmail.com" }
]
dependencies = ["tiktoken==0.5.1"]
description = "Utilities for our LLM projects (CWhy, ChatDBG, ...)."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/plasma-umass/cwhy"
"Bug Tracker" = "https://github.com/plasma-umass/cwhy/issues"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
